apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vol
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - mountPath: /cache2
          name: cache-volume
        ports:
        - containerPort: 80
      volumes:
      - name: cache-volume
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
    name: my-service
  type: NodePort
