
apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod-2
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  restartPolicy: Never
