apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    role: db 
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    role: db 
spec:
  containers:
  - name: busybox-pod
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
