apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: db
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod-1
  labels:
    app: test
spec:
  containers:
  - name: busybox-pod
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
