kind: Service
apiVersion: v1
metadata:
  name: my-service-exip
spec:
  selector:
    app: db
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 34.231.104.100
