apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: db
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  type: LoadBalancer
