apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: WHAT_IS_MY_SCHOOL
          valueFrom:
            configMapKeyRef:
              name: my-map
              key: school
  restartPolicy: Never
